# Please check the first 4 parameters, and adjust them according to your demande
NELSIN: "u11bd@nelstor0.cbu.uib.no:Personal/UiB_Goksoyr_dCod_1_2017/PCLS_BaP-EE2_RNAseq/sample_test/"
NELSOUT: "u11bd@nelstor0.cbu.uib.no:Personal/UiB_Goksoyr_dCod_1_2017/PCLS_BaP-EE2_RNAseq/oldTrans/"
PATHPREFIX: "PCLS_BaP-EE2_RNAseq/oldTrans/" 
KEY: "../key/u11bd@nelstor0.cbu.uib.no.txt"
GENOME: "../ref/genome/gadMor2.fasta"
TRANS: "../ref/trans/Gadus_morhua.gadMor1.cds.all.fa"
ANNOT: "../ref/annotation/Gadus_morhua.gadMor1.88.gtf"
HISAT2-BUILD: "../tools/hisat2-2.0.5/hisat2-build"
HISAT2: "../tools/hisat2-2.0.5/hisat2"
SAMTOOLS: "../tools/samtools-1.3.1/samtools"
NCORE: "10"
